/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopolist;

import java.io.File;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.Icon;
import static monopolist.Inicio.J3box;

/**
 *
 * @author ASUS TUF GAMING F15
 */
public class DecidirTurno extends javax.swing.JFrame {

    /**
     * Creates new form DecidirTurno
     */
    static int turnoact = 1, players = 2, i = 0;
    static int resultados[] = new int[4], comparacion[] = new int[4], turno[] = new int[4];

    public DecidirTurno() {
        initComponents();
        name1.setText(Inicio.J1Name.getText());
        name2.setText(Inicio.J2Name.getText());
        name3.setVisible(false);
        result3.setVisible(false);
        name4.setVisible(false);
        result4.setVisible(false);
        if (Inicio.J3box.isSelected()) {
            name3.setText(Inicio.J3Name.getText());
            name3.setVisible(true);
            result3.setVisible(true);
            players += 1;

        }
        if (Inicio.J4box.isSelected()) {
            name4.setText(Inicio.J4Name.getText());
            name4.setVisible(true);
            result4.setVisible(true);
            players += 1;

        }

        turnode.setText("Dados para " + Inicio.J1Name.getText());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dado1 = new javax.swing.JLabel();
        dado2 = new javax.swing.JLabel();
        lanzar = new javax.swing.JButton();
        turnode = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        result1 = new javax.swing.JLabel();
        result3 = new javax.swing.JLabel();
        result2 = new javax.swing.JLabel();
        result4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        turnos = new javax.swing.JTextArea();
        iniciar = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Decidamos los turnos!");

        dado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cara1.png"))); // NOI18N

        dado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cara1.png"))); // NOI18N

        lanzar.setBackground(new java.awt.Color(102, 255, 255));
        lanzar.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lanzar.setForeground(new java.awt.Color(0, 0, 0));
        lanzar.setText("LANZAR");
        lanzar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzarActionPerformed(evt);
            }
        });

        turnode.setBackground(new java.awt.Color(255, 51, 51));
        turnode.setFont(new java.awt.Font("Eras Bold ITC", 3, 14)); // NOI18N
        turnode.setForeground(new java.awt.Color(255, 51, 51));
        turnode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnode.setText("Dados para");

        name2.setBackground(new java.awt.Color(255, 51, 51));
        name2.setFont(new java.awt.Font("Eras Bold ITC", 3, 14)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 51, 51));
        name2.setText("Name1");

        name4.setBackground(new java.awt.Color(255, 51, 51));
        name4.setFont(new java.awt.Font("Eras Bold ITC", 3, 14)); // NOI18N
        name4.setForeground(new java.awt.Color(255, 51, 51));
        name4.setText("Name1");

        name3.setBackground(new java.awt.Color(255, 51, 51));
        name3.setFont(new java.awt.Font("Eras Bold ITC", 3, 14)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 51, 51));
        name3.setText("Name1");

        result1.setBackground(new java.awt.Color(255, 51, 51));
        result1.setFont(new java.awt.Font("Eras Bold ITC", 2, 14)); // NOI18N
        result1.setForeground(new java.awt.Color(0, 0, 0));
        result1.setText(".");

        result3.setBackground(new java.awt.Color(255, 51, 51));
        result3.setFont(new java.awt.Font("Eras Bold ITC", 2, 14)); // NOI18N
        result3.setForeground(new java.awt.Color(0, 0, 0));
        result3.setText(".");

        result2.setBackground(new java.awt.Color(255, 51, 51));
        result2.setFont(new java.awt.Font("Eras Bold ITC", 2, 14)); // NOI18N
        result2.setForeground(new java.awt.Color(0, 0, 0));
        result2.setText(".");

        result4.setBackground(new java.awt.Color(255, 51, 51));
        result4.setFont(new java.awt.Font("Eras Bold ITC", 2, 14)); // NOI18N
        result4.setForeground(new java.awt.Color(0, 0, 0));
        result4.setText(".");

        turnos.setEditable(false);
        turnos.setBackground(new java.awt.Color(204, 255, 204));
        turnos.setColumns(20);
        turnos.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        turnos.setForeground(new java.awt.Color(0, 0, 0));
        turnos.setRows(5);
        turnos.setBorder(null);
        jScrollPane1.setViewportView(turnos);

        iniciar.setBackground(new java.awt.Color(204, 255, 204));
        iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jugar.png"))); // NOI18N
        iniciar.setBorder(null);
        iniciar.setBorderPainted(false);
        iniciar.setContentAreaFilled(false);
        iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciar.setEnabled(false);
        iniciar.setOpaque(false);
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        name1.setBackground(new java.awt.Color(255, 51, 51));
        name1.setFont(new java.awt.Font("Eras Bold ITC", 3, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 51, 51));
        name1.setText("Name1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(dado2)
                        .addGap(91, 91, 91)
                        .addComponent(dado1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(turnode, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(result4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(result3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(turnode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dado2)
                            .addComponent(dado1))
                        .addGap(41, 41, 41)
                        .addComponent(lanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(result3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(result4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 73, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzarActionPerformed
        new JFXPanel();
        String dd = new File("dados.mp3").toURI().toString();
        new MediaPlayer(new Media(dd)).play();

        int d1 = (int) (Math.random() * 6) + 1;
        int d2 = (int) (Math.random() * 6) + 1;
        int result = d1 + d2;
        for (int k = 0; k < players; k++) {
            if (result == resultados[k]) {
                while (result == resultados[k]) {
                    d1 = (int) (Math.random() * 6) + 1;
                    d2 = (int) (Math.random() * 6) + 1;
                    result = d1 + d2;
                }

            }

        }

        int may = 0;

        Icon uno = new javax.swing.ImageIcon(getClass().getResource("/imagenes/cara1.png"));
        Icon dos = new javax.swing.ImageIcon(getClass().getResource("/imagenes/cara2.png"));
        Icon tres = new javax.swing.ImageIcon(getClass().getResource("/imagenes/cara3.png"));
        Icon cuatro = new javax.swing.ImageIcon(getClass().getResource("/imagenes/cara4.png"));
        Icon cinco = new javax.swing.ImageIcon(getClass().getResource("/imagenes/cara5.png"));
        Icon seis = new javax.swing.ImageIcon(getClass().getResource("/imagenes/cara6.png"));

        switch (turnoact) {
            case 1:
                if (!"".equals(Inicio.J1Name.getText())) {
                    turnode.setText("Dados para " + Inicio.J1Name.getText());
                } else {
                    turnode.setText("Dados para P1");
                }
                break;
            case 2:
                if (!"".equals(Inicio.J2Name.getText())) {
                    turnode.setText("Dados para " + Inicio.J2Name.getText());
                } else {
                    turnode.setText("Dados para P2");
                }
                break;
            case 3:
                if (!"".equals(Inicio.J3Name.getText())) {
                    turnode.setText("Dados para " + Inicio.J3Name.getText());
                } else {
                    turnode.setText("Dados para P3");
                }
                break;
            case 4:
                if (!"".equals(Inicio.J4Name.getText())) {
                    turnode.setText("Dados para " + Inicio.J4Name.getText());
                } else {
                    turnode.setText("Dados para P1");
                }
                    ;
                break;
        }

        switch (d1) {
            case 1:
                dado1.setIcon(uno);
                break;
            case 2:
                dado1.setIcon(dos);
                break;
            case 3:
                dado1.setIcon(tres);
                break;
            case 4:
                dado1.setIcon(cuatro);
                break;
            case 5:
                dado1.setIcon(cinco);
                break;
            case 6:
                dado1.setIcon(seis);
                break;
        }
        switch (d2) {
            case 1:
                dado2.setIcon(uno);
                break;
            case 2:
                dado2.setIcon(dos);
                break;
            case 3:
                dado2.setIcon(tres);
                break;
            case 4:
                dado2.setIcon(cuatro);
                break;
            case 5:
                dado2.setIcon(cinco);
                break;
            case 6:
                dado2.setIcon(seis);
                break;
        }

        switch (turnoact) {
            case 1:
                result1.setText(result + "");
                break;
            case 2:
                result2.setText(result + "");
                break;
            case 3:
                result3.setText(result + "");
                break;
            case 4:
                result4.setText(result + "");

                break;
        }
        turnoact++;
        resultados[i] = result;
        comparacion[i] = result;
        i++;
        if (turnoact > players) {
            lanzar.setEnabled(false);
            iniciar.setEnabled(true);
            int j, aux;
            for (int k = 0; k < comparacion.length - 1; k++) {
                for (j = 0; j < comparacion.length - k - 1; j++) {
                    if (comparacion[j + 1] > comparacion[j]) {
                        aux = comparacion[j + 1];
                        comparacion[j + 1] = comparacion[j];
                        comparacion[j] = aux;
                    }
                }
            }

            for (int p = 0; p < resultados.length; p++) {
                for (j = 0; j < comparacion.length; j++) {
                    if (resultados[p] == comparacion[j]) {
                        turno[p] = j + 1;

                    }
                }

            }
            turnos.setText("Turno para " + Inicio.J1Name.getText() + " : " + turno[0]);
            turnos.setText(turnos.getText() + "\nTurno para " + Inicio.J2Name.getText() + " : " + turno[1]);
            if (players == 3) {
                turnos.setText(turnos.getText() + "\nTurno para " + Inicio.J3Name.getText() + " : " + turno[2]);
            } else if (players == 4) {
                turnos.setText(turnos.getText() + "\nTurno para " + Inicio.J3Name.getText() + " : " + turno[2]);
                turnos.setText(turnos.getText() + "\nTurno para " + Inicio.J4Name.getText() + " : " + turno[3]);
            }
        }

    }//GEN-LAST:event_lanzarActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        this.setVisible(false);
        Tablero T = new Tablero();
        T.setVisible(true);

    }//GEN-LAST:event_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DecidirTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DecidirTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DecidirTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DecidirTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DecidirTurno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel dado1;
    private javax.swing.JLabel dado2;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lanzar;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel result1;
    private javax.swing.JLabel result2;
    private javax.swing.JLabel result3;
    private javax.swing.JLabel result4;
    private javax.swing.JLabel turnode;
    private javax.swing.JTextArea turnos;
    // End of variables declaration//GEN-END:variables
}
