/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopolist;

import javax.swing.Icon;
import javax.swing.JOptionPane;
import static monopolist.Tablero.BuscarTurno;
import static monopolist.Tablero.turnoac;



/**
 *
 * @author ASUS TUF GAMING F15
 */
public class propiedades extends javax.swing.JFrame {

    /**
     * Creates new form propiedades
     */
    int num=0;
    

    public propiedades() {
        initComponents();
        estado.setVisible(false);
        estado1.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fonoprop = new javax.swing.JPanel();
        barra = new javax.swing.JPanel();
        construir = new javax.swing.JButton();
        hipo = new javax.swing.JButton();
        intercambio = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        nda = new javax.swing.JButton();
        pr = new javax.swing.JButton();
        my = new javax.swing.JButton();
        st = new javax.swing.JButton();
        mrs = new javax.swing.JButton();
        oxs = new javax.swing.JButton();
        lss = new javax.swing.JButton();
        trs = new javax.swing.JButton();
        bws = new javax.swing.JButton();
        ec = new javax.swing.JButton();
        pm = new javax.swing.JButton();
        lcs = new javax.swing.JButton();
        ww = new javax.swing.JButton();
        fls = new javax.swing.JButton();
        rs = new javax.swing.JButton();
        pcd = new javax.swing.JButton();
        wr = new javax.swing.JButton();
        cvs = new javax.swing.JButton();
        fss = new javax.swing.JButton();
        bs = new javax.swing.JButton();
        pl = new javax.swing.JButton();
        vns = new javax.swing.JButton();
        wh = new javax.swing.JButton();
        mbs = new javax.swing.JButton();
        kcs = new javax.swing.JButton();
        okr = new javax.swing.JButton();
        tai = new javax.swing.JButton();
        er = new javax.swing.JButton();
        hipoPn = new javax.swing.JPanel();
        infoesp = new javax.swing.JPanel();
        colorcart = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        info1 = new javax.swing.JPanel();
        rentgrup = new javax.swing.JLabel();
        valHip = new javax.swing.JLabel();
        price4 = new javax.swing.JLabel();
        rent = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        price5 = new javax.swing.JLabel();
        free = new javax.swing.JLabel();
        info2 = new javax.swing.JPanel();
        rentesp = new javax.swing.JLabel();
        hipoes = new javax.swing.JLabel();
        estado1 = new javax.swing.JLabel();
        free2 = new javax.swing.JLabel();
        prop = new javax.swing.JLabel();
        prop1 = new javax.swing.JLabel();
        liberar = new javax.swing.JButton();
        tecar = new javax.swing.JButton();
        dineroact = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        construcPn = new javax.swing.JPanel();
        interPn = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        fonoprop.setBackground(new java.awt.Color(204, 255, 204));
        fonoprop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setBackground(new java.awt.Color(0, 148, 73));

        construir.setBackground(new java.awt.Color(0, 148, 73));
        construir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contruir.png"))); // NOI18N
        construir.setBorder(null);
        construir.setBorderPainted(false);
        construir.setContentAreaFilled(false);
        construir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        construir.setEnabled(false);
        construir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                construirActionPerformed(evt);
            }
        });

        hipo.setBackground(new java.awt.Color(0, 148, 73));
        hipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contract.png"))); // NOI18N
        hipo.setBorder(null);
        hipo.setBorderPainted(false);
        hipo.setContentAreaFilled(false);
        hipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hipo.setEnabled(false);
        hipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hipoActionPerformed(evt);
            }
        });

        intercambio.setBackground(new java.awt.Color(0, 148, 73));
        intercambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/intercambio.png"))); // NOI18N
        intercambio.setBorder(null);
        intercambio.setBorderPainted(false);
        intercambio.setContentAreaFilled(false);
        intercambio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        intercambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intercambioActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(0, 148, 73));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(construir)
                .addGap(162, 162, 162)
                .addComponent(hipo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addComponent(intercambio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(salir)
                .addGap(123, 123, 123))
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salir)
                    .addComponent(intercambio)
                    .addComponent(hipo)
                    .addComponent(construir))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        fonoprop.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1050, 120));

        nda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nda.setEnabled(false);
        nda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndaActionPerformed(evt);
            }
        });
        fonoprop.add(nda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 26, 27));

        pr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pr.setEnabled(false);
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });
        fonoprop.add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 26, 27));

        my.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        my.setEnabled(false);
        my.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myActionPerformed(evt);
            }
        });
        fonoprop.add(my, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 26, 27));

        st.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        st.setEnabled(false);
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });
        fonoprop.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 26, 27));

        mrs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mrs.setEnabled(false);
        mrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrsActionPerformed(evt);
            }
        });
        fonoprop.add(mrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 26, 27));

        oxs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oxs.setEnabled(false);
        oxs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oxsActionPerformed(evt);
            }
        });
        fonoprop.add(oxs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 26, 27));

        lss.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lss.setEnabled(false);
        lss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lssActionPerformed(evt);
            }
        });
        fonoprop.add(lss, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 26, 27));

        trs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trs.setEnabled(false);
        trs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trsActionPerformed(evt);
            }
        });
        fonoprop.add(trs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 26, 27));

        bws.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bws.setEnabled(false);
        bws.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bwsActionPerformed(evt);
            }
        });
        fonoprop.add(bws, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 26, 27));

        ec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ec.setEnabled(false);
        ec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ecMouseClicked(evt);
            }
        });
        ec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecActionPerformed(evt);
            }
        });
        fonoprop.add(ec, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 26, 27));

        pm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pm.setEnabled(false);
        pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmActionPerformed(evt);
            }
        });
        fonoprop.add(pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 26, 27));

        lcs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lcs.setEnabled(false);
        lcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcsActionPerformed(evt);
            }
        });
        fonoprop.add(lcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 26, 27));

        ww.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ww.setEnabled(false);
        ww.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wwActionPerformed(evt);
            }
        });
        fonoprop.add(ww, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 26, 27));

        fls.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fls.setEnabled(false);
        fls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flsActionPerformed(evt);
            }
        });
        fonoprop.add(fls, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 26, 27));

        rs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rs.setEnabled(false);
        rs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsActionPerformed(evt);
            }
        });
        fonoprop.add(rs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 26, 27));

        pcd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pcd.setEnabled(false);
        pcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcdActionPerformed(evt);
            }
        });
        fonoprop.add(pcd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 26, 27));

        wr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wr.setEnabled(false);
        wr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrActionPerformed(evt);
            }
        });
        fonoprop.add(wr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 26, 27));

        cvs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cvs.setEnabled(false);
        cvs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvsActionPerformed(evt);
            }
        });
        fonoprop.add(cvs, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 26, 27));

        fss.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fss.setEnabled(false);
        fss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fssActionPerformed(evt);
            }
        });
        fonoprop.add(fss, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 26, 27));

        bs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bs.setEnabled(false);
        bs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsActionPerformed(evt);
            }
        });
        fonoprop.add(bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 26, 27));

        pl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pl.setEnabled(false);
        pl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plActionPerformed(evt);
            }
        });
        fonoprop.add(pl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 26, 27));

        vns.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vns.setEnabled(false);
        vns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnsActionPerformed(evt);
            }
        });
        fonoprop.add(vns, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 26, 27));

        wh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wh.setEnabled(false);
        wh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whActionPerformed(evt);
            }
        });
        fonoprop.add(wh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 26, 27));

        mbs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mbs.setEnabled(false);
        mbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbsActionPerformed(evt);
            }
        });
        fonoprop.add(mbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 26, 27));

        kcs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kcs.setEnabled(false);
        kcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kcsActionPerformed(evt);
            }
        });
        fonoprop.add(kcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 26, 27));

        okr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okr.setEnabled(false);
        okr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okrActionPerformed(evt);
            }
        });
        fonoprop.add(okr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 26, 27));

        tai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tai.setEnabled(false);
        tai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taiActionPerformed(evt);
            }
        });
        fonoprop.add(tai, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 26, 27));

        er.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        er.setEnabled(false);
        er.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erActionPerformed(evt);
            }
        });
        fonoprop.add(er, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 26, 27));

        hipoPn.setBackground(new java.awt.Color(204, 255, 204));
        hipoPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoesp.setBackground(new java.awt.Color(255, 255, 255));
        infoesp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colorcart.setBackground(new java.awt.Color(153, 153, 255));

        titulo.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("TITULO");

        javax.swing.GroupLayout colorcartLayout = new javax.swing.GroupLayout(colorcart);
        colorcart.setLayout(colorcartLayout);
        colorcartLayout.setHorizontalGroup(
            colorcartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorcartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        colorcartLayout.setVerticalGroup(
            colorcartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorcartLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        infoesp.add(colorcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 335, -1));

        info1.setBackground(new java.awt.Color(255, 255, 255));

        rentgrup.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        rentgrup.setForeground(new java.awt.Color(0, 0, 0));
        rentgrup.setText("Renta con grupo de colores $");

        valHip.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        valHip.setForeground(new java.awt.Color(0, 0, 0));
        valHip.setText("$");

        price4.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        price4.setForeground(new java.awt.Color(0, 0, 0));
        price4.setText("Valor Hipoteca ");

        rent.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        rent.setForeground(new java.awt.Color(0, 0, 0));
        rent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rent.setText("Renta $");

        estado.setBackground(new java.awt.Color(255, 0, 0));
        estado.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        estado.setForeground(new java.awt.Color(255, 51, 51));
        estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estado.setText("HIPOTECADA");

        price5.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        price5.setForeground(new java.awt.Color(0, 0, 0));
        price5.setText("Valor liberar");

        free.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        free.setForeground(new java.awt.Color(0, 0, 0));
        free.setText("$");

        javax.swing.GroupLayout info1Layout = new javax.swing.GroupLayout(info1);
        info1.setLayout(info1Layout);
        info1Layout.setHorizontalGroup(
            info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info1Layout.createSequentialGroup()
                .addGroup(info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(info1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(info1Layout.createSequentialGroup()
                                    .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valHip, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(rentgrup, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info1Layout.createSequentialGroup()
                                    .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(free, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        info1Layout.setVerticalGroup(
            info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentgrup, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valHip, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(free, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        infoesp.add(info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 330, 260));

        info2.setBackground(new java.awt.Color(255, 255, 255));

        rentesp.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        rentesp.setForeground(new java.awt.Color(0, 0, 0));
        rentesp.setText("Renta con grupo de colores $");

        hipoes.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        hipoes.setForeground(new java.awt.Color(0, 0, 0));
        hipoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hipoes.setText("Valor Hipoteca: $");

        estado1.setBackground(new java.awt.Color(255, 0, 0));
        estado1.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        estado1.setForeground(new java.awt.Color(255, 51, 51));
        estado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estado1.setText("HIPOTECADA");

        free2.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        free2.setForeground(new java.awt.Color(0, 0, 0));
        free2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        free2.setText("Valor liberar: $");

        javax.swing.GroupLayout info2Layout = new javax.swing.GroupLayout(info2);
        info2.setLayout(info2Layout);
        info2Layout.setHorizontalGroup(
            info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hipoes, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rentesp, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(free2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        info2Layout.setVerticalGroup(
            info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info2Layout.createSequentialGroup()
                .addComponent(rentesp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hipoes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(free2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        infoesp.add(info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 330, 260));

        hipoPn.add(infoesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 58, -1, 422));

        prop.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        prop.setForeground(new java.awt.Color(255, 51, 51));
        prop.setText("HIPOTECAR");
        hipoPn.add(prop, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 278, -1));

        prop1.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        prop1.setForeground(new java.awt.Color(153, 153, 255));
        prop1.setText("Propiedades");
        hipoPn.add(prop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 278, -1));

        liberar.setBackground(new java.awt.Color(102, 255, 102));
        liberar.setFont(new java.awt.Font("Eras Bold ITC", 3, 18)); // NOI18N
        liberar.setForeground(new java.awt.Color(255, 255, 255));
        liberar.setText("LIBERAR");
        liberar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        liberar.setEnabled(false);
        liberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberarActionPerformed(evt);
            }
        });
        hipoPn.add(liberar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 170, 50));

        tecar.setBackground(new java.awt.Color(255, 51, 51));
        tecar.setFont(new java.awt.Font("Eras Bold ITC", 3, 18)); // NOI18N
        tecar.setForeground(new java.awt.Color(255, 255, 255));
        tecar.setText("HIPOTECAR");
        tecar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tecar.setEnabled(false);
        tecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecarActionPerformed(evt);
            }
        });
        hipoPn.add(tecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 170, 50));

        dineroact.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        dineroact.setForeground(new java.awt.Color(0, 204, 0));
        dineroact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dineroact.setText("$");
        hipoPn.add(dineroact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        titulo2.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 51, 51));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("TU CARTERA:");
        hipoPn.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        fonoprop.add(hipoPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        construcPn.setBackground(new java.awt.Color(255, 204, 102));
        construcPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fonoprop.add(construcPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        interPn.setBackground(new java.awt.Color(102, 255, 255));
        interPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fonoprop.add(interPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fonoprop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fonoprop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void intercambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intercambioActionPerformed
        interPn.setVisible(true);
        hipoPn.setVisible(false);
        construcPn.setVisible(false);
    }//GEN-LAST:event_intercambioActionPerformed

    private void construirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_construirActionPerformed
        interPn.setVisible(false);
        hipoPn.setVisible(false);
        construcPn.setVisible(true);
    }//GEN-LAST:event_construirActionPerformed

    private void hipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hipoActionPerformed
        interPn.setVisible(false);
        hipoPn.setVisible(true);
        construcPn.setVisible(false);
    }//GEN-LAST:event_hipoActionPerformed

    private void ecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ecMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ecMouseClicked

    private void okrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okrActionPerformed
        Tablero.Tab.BuscarPresionando(1);
        
        num=1;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
        
    }//GEN-LAST:event_okrActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Jugadores tempo = BuscarTurno(turnoac, Tablero.J);
        
        if(tempo.enApuros==true & tempo.dinero>=tempo.deuda){
            tempo.dinero-=tempo.deuda;
            tempo.VerDinero.setText("$"+tempo.dinero);
            tempo.debe.dinero+=tempo.deuda;
            tempo.debe.VerDinero.setText("$"+tempo.debe.dinero);
            
            Icon pay = new javax.swing.ImageIcon(getClass().getResource("/imagenes/pay.png"));
            JOptionPane.showMessageDialog(null, "<html><p style=\" color:red; font:15px ;font face='Eras Bold'; \">"+tempo.nick+" pagó su deuda con "+tempo.debe.nick+" por $" + tempo.deuda + "<p><html>",
                                    "PAGAR DEUDA ", JOptionPane.PLAIN_MESSAGE, pay);
                                    tempo.deuda=0;
            Tablero.Historial.setText(Tablero.Historial.getText() + "\n" + tempo.nick + " pagó renta por $" + tempo.deuda);
            tempo.debe=null;
            tempo.deuda=0;
            tempo.enApuros=false;
            if(Tablero.d1 != Tablero.d2){
                Tablero.pasar.setEnabled(true);
            }else{
                Tablero.lanzar.setEnabled(true);
            }
            
            
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_salirActionPerformed

    private void wrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrActionPerformed
        Tablero.Tab.BuscarPresionando(3);
        num=3;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
        
    }//GEN-LAST:event_wrActionPerformed

    private void plActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plActionPerformed
        Tablero.Tab.BuscarPresionando(37);
        num=37;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
        
    }//GEN-LAST:event_plActionPerformed

    private void myActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myActionPerformed
        Tablero.Tab.BuscarPresionando(39);
        num=39;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_myActionPerformed

    private void taiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taiActionPerformed
       Tablero.Tab.BuscarPresionando(6);
       num=6;
       if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_taiActionPerformed

    private void erActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erActionPerformed
        Tablero.Tab.BuscarPresionando(8);
        num=8;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_erActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        Tablero.Tab.BuscarPresionando(9);
        num=9;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_prActionPerformed

    private void pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmActionPerformed
        Tablero.Tab.BuscarPresionando(11);
        num=11;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_pmActionPerformed

    private void whActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whActionPerformed
        Tablero.Tab.BuscarPresionando(13);
        num=13;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_whActionPerformed

    private void ndaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndaActionPerformed
        Tablero.Tab.BuscarPresionando(14);
        num=14;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_ndaActionPerformed

    private void bwsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bwsActionPerformed
        Tablero.Tab.BuscarPresionando(16);
        num=16;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_bwsActionPerformed

    private void mbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbsActionPerformed
        Tablero.Tab.BuscarPresionando(18);
        num=18;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_mbsActionPerformed

    private void vnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnsActionPerformed
        Tablero.Tab.BuscarPresionando(19);
        num=19;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_vnsActionPerformed

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
       Tablero.Tab.BuscarPresionando(21);
       num=21;
       if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_stActionPerformed

    private void flsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flsActionPerformed
       Tablero.Tab.BuscarPresionando(23);
       num=23;
       if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_flsActionPerformed

    private void trsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trsActionPerformed
        Tablero.Tab.BuscarPresionando(24);
        num=24;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_trsActionPerformed

    private void lcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcsActionPerformed
        Tablero.Tab.BuscarPresionando(26);
        num=26;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_lcsActionPerformed

    private void cvsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvsActionPerformed
        Tablero.Tab.BuscarPresionando(27);
        num=27;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_cvsActionPerformed

    private void pcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcdActionPerformed
        Tablero.Tab.BuscarPresionando(29);
        num=29;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_pcdActionPerformed

    private void rsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsActionPerformed
        Tablero.Tab.BuscarPresionando(31);
        num=31;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
        
    }//GEN-LAST:event_rsActionPerformed

    private void oxsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oxsActionPerformed
        Tablero.Tab.BuscarPresionando(32);
        num=32;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_oxsActionPerformed

    private void bsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsActionPerformed
        Tablero.Tab.BuscarPresionando(34);
        num=34;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_bsActionPerformed

    private void kcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kcsActionPerformed
        Tablero.Tab.BuscarPresionando(5);
        num=5;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(false);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_kcsActionPerformed

    private void mrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrsActionPerformed
        Tablero.Tab.BuscarPresionando(15);
        num=15;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_mrsActionPerformed

    private void fssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fssActionPerformed
        Tablero.Tab.BuscarPresionando(25);
        num=25;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_fssActionPerformed

    private void lssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lssActionPerformed
        Tablero.Tab.BuscarPresionando(35);
        num=35;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_lssActionPerformed

    private void ecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecActionPerformed
        Tablero.Tab.BuscarPresionando(12);
        num=12;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
            estado1.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_ecActionPerformed

    private void wwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wwActionPerformed
        Tablero.Tab.BuscarPresionando(28);
        num=28;
        if(Tablero.Tab.BuscarPorNumer(num).Casilla.hipotecada==true){
            estado.setVisible(true);
        }else{
            estado.setVisible(false);
            estado1.setVisible(false);
        }
    }//GEN-LAST:event_wwActionPerformed

    private void tecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecarActionPerformed
         Tablero.Tab.BuscarPorNumer(num).Casilla.Hipotecar();
         estado.setVisible(true);
         estado1.setVisible(true);
         
    }//GEN-LAST:event_tecarActionPerformed

    private void liberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberarActionPerformed
        Tablero.Tab.BuscarPorNumer(num).Casilla.liberar();
        estado.setVisible(false);
        estado1.setVisible(false);
    }//GEN-LAST:event_liberarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(propiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(propiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(propiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(propiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new propiedades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    public static javax.swing.JButton bs;
    public static javax.swing.JButton bws;
    public static javax.swing.JPanel colorcart;
    private javax.swing.JPanel construcPn;
    private javax.swing.JButton construir;
    public static javax.swing.JButton cvs;
    public static javax.swing.JLabel dineroact;
    public static javax.swing.JButton ec;
    public static javax.swing.JButton er;
    public static javax.swing.JLabel estado;
    public static javax.swing.JLabel estado1;
    public static javax.swing.JButton fls;
    private javax.swing.JPanel fonoprop;
    public static javax.swing.JLabel free;
    public static javax.swing.JLabel free2;
    public static javax.swing.JButton fss;
    private javax.swing.JButton hipo;
    private javax.swing.JPanel hipoPn;
    public static javax.swing.JLabel hipoes;
    public static javax.swing.JPanel info1;
    public static javax.swing.JPanel info2;
    public static javax.swing.JPanel infoesp;
    private javax.swing.JPanel interPn;
    private javax.swing.JButton intercambio;
    public static javax.swing.JButton kcs;
    public static javax.swing.JButton lcs;
    public static javax.swing.JButton liberar;
    public static javax.swing.JButton lss;
    public static javax.swing.JButton mbs;
    public static javax.swing.JButton mrs;
    public static javax.swing.JButton my;
    public static javax.swing.JButton nda;
    public static javax.swing.JButton okr;
    public static javax.swing.JButton oxs;
    public static javax.swing.JButton pcd;
    public static javax.swing.JButton pl;
    public static javax.swing.JButton pm;
    public static javax.swing.JButton pr;
    public static javax.swing.JLabel price4;
    public static javax.swing.JLabel price5;
    private javax.swing.JLabel prop;
    private javax.swing.JLabel prop1;
    public static javax.swing.JLabel rent;
    public static javax.swing.JLabel rentesp;
    public static javax.swing.JLabel rentgrup;
    public static javax.swing.JButton rs;
    public static javax.swing.JButton salir;
    public static javax.swing.JButton st;
    public static javax.swing.JButton tai;
    public static javax.swing.JButton tecar;
    public static javax.swing.JLabel titulo;
    public static javax.swing.JLabel titulo2;
    public static javax.swing.JButton trs;
    public static javax.swing.JLabel valHip;
    public static javax.swing.JButton vns;
    public static javax.swing.JButton wh;
    public static javax.swing.JButton wr;
    public static javax.swing.JButton ww;
    // End of variables declaration//GEN-END:variables
}
